# Generated by Django 4.2.4 on 2024-05-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0003_alter_member_data_member_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_data',
            name='member_password',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='show',
            field=models.CharField(choices=[('coming_soon', '即將上映'), ('showing', '現正熱映'), ('removed', '下架電影')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='staff_department',
            field=models.CharField(choices=[('it', 'IT部門'), ('hr', '人事部門')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='staff_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='staff_password',
            field=models.CharField(max_length=25),
        ),
    ]
