# Generated by Django 4.2.6 on 2024-06-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0004_alter_member_data_member_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_data',
            name='staff_account',
            field=models.CharField(default=1, max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='staff_department',
            field=models.CharField(choices=[('it', 'IT部門'), ('hr', '人事部門')], max_length=200),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='staff_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='staff_password',
            field=models.CharField(max_length=200),
        ),
    ]
